// Generated by uniffi-bindgen-react-native
#include "react-native-automerge-generated.h"
#include "generated/automerge.hpp"

namespace automergegenerated {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeAutomerge::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}