// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-automerge-generated.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNAutomergeGeneratedSpec.h"

@interface AutomergeGenerated : NSObject <NativeAutomergeGeneratedSpec>
#else
#import <React/RCTBridgeModule.h>

@interface AutomergeGenerated : NSObject <RCTBridgeModule>
#endif

@end